/**
 * This class is generated by jOOQ
 */
package org.tmarcus.sandbox.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookRecord extends org.jooq.impl.UpdatableRecordImpl<org.tmarcus.sandbox.data.tables.records.BookRecord> implements org.jooq.Record3<org.jooq.types.UInteger, java.lang.String, java.sql.Date> {

	private static final long serialVersionUID = 517717301;

	/**
	 * Setter for <code>jooq-sample.book.id</code>.
	 */
	public void setId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jooq-sample.book.id</code>.
	 */
	public org.jooq.types.UInteger getId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>jooq-sample.book.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jooq-sample.book.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>jooq-sample.book.publish_date</code>.
	 */
	public void setPublishDate(java.sql.Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>jooq-sample.book.publish_date</code>.
	 */
	public java.sql.Date getPublishDate() {
		return (java.sql.Date) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, java.lang.String, java.sql.Date> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<org.jooq.types.UInteger, java.lang.String, java.sql.Date> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return org.tmarcus.sandbox.data.tables.Book.BOOK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.tmarcus.sandbox.data.tables.Book.BOOK.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field3() {
		return org.tmarcus.sandbox.data.tables.Book.BOOK.PUBLISH_DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value3() {
		return getPublishDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookRecord value1(org.jooq.types.UInteger value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookRecord value3(java.sql.Date value) {
		setPublishDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookRecord values(org.jooq.types.UInteger value1, java.lang.String value2, java.sql.Date value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BookRecord
	 */
	public BookRecord() {
		super(org.tmarcus.sandbox.data.tables.Book.BOOK);
	}

	/**
	 * Create a detached, initialised BookRecord
	 */
	public BookRecord(org.jooq.types.UInteger id, java.lang.String name, java.sql.Date publishDate) {
		super(org.tmarcus.sandbox.data.tables.Book.BOOK);

		setValue(0, id);
		setValue(1, name);
		setValue(2, publishDate);
	}
}
