/**
 * This class is generated by jOOQ
 */
package org.tmarcus.sandbox.data;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooq_sample extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1773785984;

	/**
	 * The reference instance of <code>jooq-sample</code>
	 */
	public static final Jooq_sample JOOQ_SAMPLE = new Jooq_sample();

	/**
	 * No further instances allowed
	 */
	private Jooq_sample() {
		super("jooq-sample");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.tmarcus.sandbox.data.tables.Book.BOOK);
	}
}
