/**
 * This class is generated by jOOQ
 */
package org.tmarcus.sandbox.data;

/**
 * A class modelling foreign key relationships between tables of the <code>jooq-sample</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<org.tmarcus.sandbox.data.tables.records.BookRecord, org.jooq.types.UInteger> IDENTITY_BOOK = Identities0.IDENTITY_BOOK;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<org.tmarcus.sandbox.data.tables.records.BookRecord> KEY_BOOK_PRIMARY = UniqueKeys0.KEY_BOOK_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<org.tmarcus.sandbox.data.tables.records.BookRecord, org.jooq.types.UInteger> IDENTITY_BOOK = createIdentity(org.tmarcus.sandbox.data.tables.Book.BOOK, org.tmarcus.sandbox.data.tables.Book.BOOK.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.tmarcus.sandbox.data.tables.records.BookRecord> KEY_BOOK_PRIMARY = createUniqueKey(org.tmarcus.sandbox.data.tables.Book.BOOK, org.tmarcus.sandbox.data.tables.Book.BOOK.ID);
	}
}
