/**
 * This class is generated by jOOQ
 */
package org.tmarcus.sandbox.data;

/**
 * Convenience access to all tables in jooq-sample
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jooq-sample.book
	 */
	public static final org.tmarcus.sandbox.data.tables.Book BOOK = org.tmarcus.sandbox.data.tables.Book.BOOK;
}
