/**
 * This class is generated by jOOQ
 */
package org.tmarcus.sandbox.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book extends org.jooq.impl.TableImpl<org.tmarcus.sandbox.data.tables.records.BookRecord> {

	private static final long serialVersionUID = -1126045048;

	/**
	 * The reference instance of <code>jooq-sample.book</code>
	 */
	public static final org.tmarcus.sandbox.data.tables.Book BOOK = new org.tmarcus.sandbox.data.tables.Book();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.tmarcus.sandbox.data.tables.records.BookRecord> getRecordType() {
		return org.tmarcus.sandbox.data.tables.records.BookRecord.class;
	}

	/**
	 * The column <code>jooq-sample.book.id</code>.
	 */
	public final org.jooq.TableField<org.tmarcus.sandbox.data.tables.records.BookRecord, org.jooq.types.UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>jooq-sample.book.name</code>.
	 */
	public final org.jooq.TableField<org.tmarcus.sandbox.data.tables.records.BookRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(128).nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>jooq-sample.book.publish_date</code>.
	 */
	public final org.jooq.TableField<org.tmarcus.sandbox.data.tables.records.BookRecord, java.sql.Date> PUBLISH_DATE = createField("publish_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * Create a <code>jooq-sample.book</code> table reference
	 */
	public Book() {
		this("book", null);
	}

	/**
	 * Create an aliased <code>jooq-sample.book</code> table reference
	 */
	public Book(java.lang.String alias) {
		this(alias, org.tmarcus.sandbox.data.tables.Book.BOOK);
	}

	private Book(java.lang.String alias, org.jooq.Table<org.tmarcus.sandbox.data.tables.records.BookRecord> aliased) {
		this(alias, aliased, null);
	}

	private Book(java.lang.String alias, org.jooq.Table<org.tmarcus.sandbox.data.tables.records.BookRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.tmarcus.sandbox.data.Jooq_sample.JOOQ_SAMPLE, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.tmarcus.sandbox.data.tables.records.BookRecord, org.jooq.types.UInteger> getIdentity() {
		return org.tmarcus.sandbox.data.Keys.IDENTITY_BOOK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.tmarcus.sandbox.data.tables.records.BookRecord> getPrimaryKey() {
		return org.tmarcus.sandbox.data.Keys.KEY_BOOK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.tmarcus.sandbox.data.tables.records.BookRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.tmarcus.sandbox.data.tables.records.BookRecord>>asList(org.tmarcus.sandbox.data.Keys.KEY_BOOK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.tmarcus.sandbox.data.tables.Book as(java.lang.String alias) {
		return new org.tmarcus.sandbox.data.tables.Book(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.tmarcus.sandbox.data.tables.Book rename(java.lang.String name) {
		return new org.tmarcus.sandbox.data.tables.Book(name, null);
	}
}
